name: Flask App Test

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app/

        strategy:
            matrix:
                python-version: [3.8]

        env:
            MODE: "dev"

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{matrix.python-version}}

            - name: install dependency
              run: |
                 python -m pip install --upgrade pip
                 pip install -r ../requirements.txt

            - name: execute unitest
              run: python ./main_test.py
