# .github/workflows/js-security.yml

name: JavaScript/TypeScript Security Analysis

on: [push, pull_request]

jobs:
  security:
    name: Run npm audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the Node.js version of your project

    - name: Install dependencies
      run: npm install

    - name: Run npm audit
      run: |
        npm audit
